"""Exception hierarchy (spec §5.1)."""
from __future__ import annotations


class DemoError(Exception):
    def __init__(self, message: str, hint: str = "") -> None:
        super().__init__(message)
        self.message = message
        self.hint = hint


class InputValidationError(DemoError): ...
class EncodingDetectionError(DemoError): ...
class DialectDetectionError(DemoError): ...
class HeaderMappingError(DemoError): ...
class TemplateSchemaError(DemoError): ...
class MappingFileError(DemoError): ...
class RowCountMismatchError(DemoError): ...
class TemplateExistsError(DemoError): ...
